apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-password
  namespace: ca3-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: mongodb-password
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: ca3-mongodb-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-key
  namespace: ca3-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: api-key
    template:
      type: Opaque
      data:
        key: "{{ .key }}"
  data:
  - secretKey: key
    remoteRef:
      key: ca3-metals-api-key