---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: producer-monitor
  namespace: ca3-app
  labels:
    app: producer
    tier: ingestion
    release: prometheus
spec:
  selector:
    matchLabels:
      app: producer
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: processor-monitor
  namespace: ca3-app
  labels:
    app: processor
    tier: processing
    release: prometheus
spec:
  selector:
    matchLabels:
      app: processor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
